package network.palace.parkmanager.handlers;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents reward data with various ranks for a specific context
 * such as permissions, achievements, or status levels.
 *
 * <p>This class defines the following reward ranks:</p>
 * <ul>
 *   <li>{@code settler} - Represents the "Settler" rank.</li>
 *   <li>{@code dweller} - Represents the "Dweller" rank.</li>
 *   <li>{@code noble} - Represents the "Noble" rank.</li>
 *   <li>{@code majestic} - Represents the "Majestic" rank.</li>
 *   <li>{@code honorable} - Represents the "Honorable" rank.</li>
 * </ul>
 *
 * <p>Each rank is identified by a long integer, which can be used
 * for storing identifiers, points, or similar attributes necessary
 * for achievement or ranking systems.</p>
 *
 * <p>This class is immutable and promotes encapsulation through the use
 * of getters and setters from Lombok annotations.</p>
 */
@Getter
@Setter
@AllArgsConstructor
public class RewardData {
    /**
     * Represents the "Settler" rank within the reward system.
     *
     * <p>The {@code settler} variable is a {@code long} that uniquely identifies
     * and defines attributes or points associated with the "Settler" reward rank.</p>
     *
     * <p>The "Settler" rank may be part of a hierarchy of ranks used to determine
     * permissions, achievements, or other status indicators in the context of
     * reward or ranking systems.</p>
     *
     * <ul>
     *   <li>Used to store identifier or points related to the "Settler" rank.</li>
     *   <li>Operates alongside other rank definitions such as "Dweller", "Noble",
     *       "Majestic", and "Honorable".</li>
     * </ul>
     */
    private long settler;

    /**
     * Represents the "Dweller" rank in the reward data hierarchy.
     *
     * <p>The {@code dweller} variable is a long integer used to store
     * the associated rank value or identifier within the reward system.
     * It is part of the ranking system that includes other ranks such as
     * {@code settler}, {@code noble}, {@code majestic}, and {@code honorable}.</p>
     *
     * <p>This rank can be used in contexts such as:
     * <ul>
     *   <li>Measuring progress or achievements within a permission or reward system.</li>
     *   <li>Assigning levels for user status or role-based attributes.</li>
     *   <li>Storing numeric values that represent the position within a hierarchy.</li>
     * </ul>
     *
     * <p>Part of an immutable reward data model, this field's value is encapsulated
     * and accessed through autogenerated getter and setter methods provided by Lombok annotations.</p>
     */
    private long dweller;

    /**
     * Represents the "Noble" rank within the {@code RewardData} class.
     *
     * <p>This variable holds a {@code long} value that uniquely identifies or
     * quantifies attributes associated with the "Noble" rank. It could represent
     * points, identifiers, or similar contextual data for ranking and achievement systems.</p>
     *
     * <p>The "Noble" rank is part of a hierarchy within the {@code RewardData} class, which includes
     * other ranks like "Settler," "Dweller," "Majestic," and "Honorable." Each rank is distinguished and
     * managed as an independent attribute for encapsulating associated data.</p>
     *
     * <ul>
     *   <li>Defines and stores information specific to the "Noble" rank.</li>
     *   <li>Ensures separation of rank attributes for better encapsulation and modular design.</li>
     *   <li>Promotes the management of rank-related data with precise granularity.</li>
     * </ul>
     */
    private long noble;

    /**
     * Represents the "Majestic" rank or level in the reward data.
     *
     * <p>This variable is used to store a long integer value associated with the "Majestic" rank,
     * which could represent an identifier, points, or other attributes related to this specific rank
     * in the context of permissions, achievements, or status levels.</p>
     *
     * <p>The "Majestic" rank is part of a predefined hierarchy which also includes the following ranks:</p>
     * <ul>
     *   <li>Settler</li>
     *   <li>Dweller</li>
     *   <li>Noble</li>
     *   <li>Honorable</li>
     * </ul>
     *
     * <p>This variable encapsulates a specific rank to facilitate better organization,
     * management, and retrieval of rank-related data in the application.</p>
     */
    private long majestic;

    /**
     * Represents the "Honorable" rank within the context of reward data.
     *
     * <p>This field identifies the "Honorable" tier, typically as an indicator
     * for achievements, permissions, or status levels tied to this specific rank.
     * It employs a long integer to store its associated value, which may denote
     * identifiers, points, or other rank-relevant attributes.</p>
     *
     * <p>Key aspects of the "Honorable" rank:</p>
     * <ul>
     *   <li>It is one of the reward ranks defined in the system, alongside others
     *       such as "Settler," "Dweller," "Noble," and "Majestic."</li>
     *   <li>Utilized to distinguish users, entities, or contexts associated with
     *       higher levels of achievement or honor.</li>
     *   <li>Can be leveraged in systems needing rank-specific behavior or
     *       categorization.</li>
     * </ul>
     */
    private long honorable;
}
